### ISSUE TITLE
AttributeError: _call_infos when running with pytester plugin

### ISSUE THREAD

**Issue by DRMacIver** [box/flaky#82]
I'm using the pytester plugin to test my pytest plugin for Hypothesis. If I happen to have flaky installed when I do, it goes a bit wrong.

If I run the following test while flaky is installed:

```python
import pytest

pytest_plugins = str('pytester')

TESTSUITE = """
def test_a_thing():
    pass

"""


def test_output_without_capture(testdir):
    script = testdir.makepyfile(TESTSUITE)
    result = testdir.runpytest(script, '--verbose', '--capture', 'fd')
    assert result.ret == 0
```

I get the following output:

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/david/projects/scratch/flakytest/flaker/lib/python2.7/site-packages/_pytest/main.py", line 90, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/david/projects/scratch/flakytest/flaker/lib/python2.7/site-packages/_pytest/main.py", line 121, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/david/projects/scratch/flakytest/flaker/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/david/projects/scratch/flakytest/flaker/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/david/projects/scratch/flakytest/flaker/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/david/projects/scratch/flakytest/flaker/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/david/projects/scratch/flakytest/flaker/lib/python2.7/site-packages/_pytest/main.py", line 146, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/home/david/projects/scratch/flakytest/flaker/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/david/projects/scratch/flakytest/flaker/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/david/projects/scratch/flakytest/flaker/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/david/projects/scratch/flakytest/flaker/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 595, in execute
INTERNALERROR>     return _wrapped_call(hook_impl.function(*args), self.execute)
INTERNALERROR>   File "/home/david/projects/scratch/flakytest/flaker/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 253, in _wrapped_call
INTERNALERROR>     return call_outcome.get_result()
INTERNALERROR>   File "/home/david/projects/scratch/flakytest/flaker/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "/home/david/projects/scratch/flakytest/flaker/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 264, in __init__
INTERNALERROR>     self.result = func()
INTERNALERROR>   File "/home/david/projects/scratch/flakytest/flaker/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/david/projects/scratch/flakytest/flaker/lib/python2.7/site-packages/flaky/flaky_pytest_plugin.py", line 98, in pytest_runtest_protocol
INTERNALERROR>     del self._call_infos
INTERNALERROR> AttributeError: _call_infos
```

Note: The test passes (I'm not totally sure why), but it still causes this output.

I think this is because pytester is running in inprocess mode, so the plugin is being called recursively and trying to delete the attribute twice. Indeed, adding the flags "-p pytester --runpytest subprocess" to get pytester to default to subprocess mode causes the problem to go away.

**Comment by Jeff-Meadows** [comment]
How strange, it reuses your loaded plugins in inprocess mode. Fix incoming.
